### ISSUE TITLE
Update Fedora SciTE package?

### ISSUE THREAD

**Issue by ryanpcmcquen** [opuk/satellite#1]
Sorry to contact you this way, but I am wondering if you are the maintainer of SciTE for Fedora, and if so, will you update it?

**Comment by opuk** [comment]
Hello,
No worries, I was the maintainer of SciTE in Fedora but since I'm no longer using it my self and lack of time I'm unfortunately no longer able to maintain it. It is orphaned, which means that any maintainer is free to pick it up.
